#!/bin/sh

# (re)load sxhkd for keybinds
# pkill sxhkd; sxhkd -c ~/.config/yaxwm/sxhkdrc &
pkill sxhkd; sxhkd &

pkill polybar; polybar yaxwm-bar &

# bspwm requires this - can be run from bspwmrc; doesn't seem to matter for rest
xsetroot -cursor_name left_ptr &

# determine where to place the log file
logfile="$HOME/.yaxcmd.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/yaxcmd.log"
: > "$logfile"

# Window manager configuration run as a compound command to
# redirect all output to a file instead of redirecting each command.
# Not needed but it's nice to be able to tell when there are errors.
{
	# workspace settings
	# ------------------------
	# default values to use when allocating new workspaces
	# yaxcmd set wsdef layout=tile master=1 stack=3 gap=0 split=0.55 ssplit=0.50
	#yaxcmd set wsdef layout=tile master=1 stack=3 split=0.55 ssplit=0.50
	#yaxcmd set wsdef pad l=4 r=4 t=4 b=4
    
	# initialize 10 workspaces (1-10)
	yaxcmd set numws=10

	# rename workspace(s)
	yaxcmd set ws=1 name="1" ws=2 name="2" ws=3 name="3"

	# set workspace 10 to use some padding and gaps
	yaxcmd set ws=10 pad l=4 r=4 t=4 b=4
	yaxcmd set ws=10 gap width=4

	# misc settings
	# ---------------------
	# ignore size hints on tiled windows, focus windows when
	# receiving activation, and enable focus-follows-mouse
	yaxcmd set tile_hints=0 focus_urgent=1 focus_mouse=0

	# minimum width/height for resizing, and minimum allowed on-screen
	# when moving (defines how much a window can be moved off-screen)
	yaxcmd set win_minwh=50 win_minxy=10

	# define mouse mod and move/resize buttons
	yaxcmd set mouse mod=alt move=button1 resize=button3


	# borders and gaps
	# ---------

	yaxcmd set border width 2

	# disable gaps and borders in single window layouts
	yaxcmd set smart_gap=true smart_border=true

	# set border colour for each window state
	yaxcmd set border colour focus='#343536' unfocus='#131313' urgent='#D21E25'


	# window rules
	# --------------
	# open window(s) on a specific workspace (assigned monitor)
	yaxcmd rule class="^gimp$" ws=4
	yaxcmd rule class="^(audacious|Deadbeef|vlc|mpv)$" ws=10

	# open window(s) on a monitor by number or name (active workspace on monitor)
	yaxcmd rule class="^firefox$"  mon=1
	# yaxcmd rule class="^chromium$" mon="HDMI-A-0"

	# open window(s) and use a callback function (defined in config.h)
	# eg. mpv --x11-name=albumart /path/to/media
	# yaxcmd rule class="^mpv$" instance="^albumart$" float callback=albumart bw=0

	# open window(s) in a floating state
	yaxcmd rule class="^(pavucontrol|transmission-gtk|steam|lxappearance)$" float
	yaxcmd rule class="^(vlc|audacious|deadbeef|mpv)$" float

	# open window(s) with a specific geometry and coordinates (floating only!)
	#yaxcmd rule class="^google-chrome$" title="^open files$" float w=1280 h=720

	# open window(s) with sticky and floating enabled to view on all workspaces.
	#yaxcmd rule class="^stickyterm$" stick float w=1280 h=720

	# update or remove an existing rule with the same match patterns
	# yaxcmd rule class="^firefox$" mon="My New Monitor"
	# yaxcmd rule remove class="^firefox$"

} >> "$logfile" 2>&1 # append responses

# inform of any errors in a notification
if grep -q 'error:' "$logfile"; then
	hash notify-send && notify-send -t 0 -u critical "Yaxwmrc Has Errors" \
		"$(awk '/error:/ {sub(/^error: /, ""); print}' "$logfile")"
	exit 1
fi

exit 0
