#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

pkill -x polybar &
pkill -x sxhkd &
pkill -x conky &
pkill -x juiced &

# Change your keymap:
xmodmap "$HOME/.Xmodmap"
xrdb -l "$HOME/.Xresources"
fbsetroot -solid "#333366" &

# battery monitor
juiced -d

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# set wallpaper
# (sleep 2s && fbsetbg -c $HOME/wallpaper/falcon.jpg) &
(sleep 2s && fbsetbg -c -r "$HOME/wallpaper/") &

# 3rd party apps
# (sleep 2s && conky -dc $HOME/.conky10fboxrc) &
# (sleep 2s && connman-gtk --tray) &

# panels
(sleep 2s && polybar fboxbar) &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "$HOME/.fluxbox/log"
