#!/bin/sh

# example dkrc to show some basic command usage and error reporting

# determine where to place the log file
logfile="$HOME/.dkrc.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/dkrc.log"
: > "$logfile"

# change mouse from an "X"
xsetroot -cursor_name left_ptr

# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd &
fi

# polybar
pkill polybar ; polybar dkwm-bar &

{ # compound command to redirect all output

	# workspace settings
	# ------------------------

	# initialize 10 workspaces (1-10)
	dkcmd set numws=10

	# default workspace '_' values used when allocating new workspaces
	# can be applied to all existing workspaces when passed 'apply' after ws=_
	dkcmd set ws=_ apply layout=tile master=1 stack=3 gap=0 msplit=0.5 ssplit=0.5

	# change workspace names
	dkcmd set \
		ws=1  name="1" \
		ws=2  name="2" \
		ws=3  name="3" \
		ws=4  name="4" \
		ws=5  name="5" \
		ws=6  name="6" \
		ws=7  name="7" \
		ws=8  name="8" \
		ws=9  name="9" \
		ws=10 name="10"

	# change workspace layouts
	# tile,mono,grid,spiral,dwindle,
	dkcmd set ws=1 layout = tile
	dkcmd set ws=2 layout = tile
	dkcmd set ws=3 layout = mono
	dkcmd set ws=4 layout = mono
	dkcmd set ws=5 layout = mono
	dkcmd set ws=6 layout = tile
	dkcmd set ws=7 layout = dwindle
	dkcmd set ws=8 layout = spiral
	dkcmd set ws=9 layout = none 
	dkcmd set ws=10 layout=grid

	# use grid layout, padding, and gaps on workspace 10
	dkcmd set ws=10 layout=grid pad left=10 right=10 top=10 bottom=10 gap width=5

	# use static workspaces (not default)
	dkcmd set static_ws=false

	# assign workspaces to monitors (requires static_ws=true)
	# mon1='DisplayPort-0'
	# mon2='HDMI-A-0'
	# dkcmd set \
	# 	ws=1  mon=$mon1 \
	# 	ws=2  mon=$mon1 \
	# 	ws=3  mon=$mon1 \
	# 	ws=4  mon=$mon1 \
	# 	ws=5  mon=$mon1 \
	# 	ws=6  mon=$mon2 \
	# 	ws=7  mon=$mon2 \
	# 	ws=8  mon=$mon2 \
	# 	ws=9  mon=$mon2 \
	# 	ws=10 mon=$mon2


	# global settings
	# ---------------------

	# focus windows when receiving activation and enable focus-follows-mouse
	dkcmd set focus_open=true focus_urgent=true focus_mouse=false

	# place clients at the tail and ignore size hints on tiled windows
	dkcmd set tile_tohead=0 tile_hints=false

	# minimum width/height for resizing, and minimum allowed on-screen when moving
	dkcmd set win_minwh=50 win_minxy=10

	# disable gaps and borders in single window layouts
	dkcmd set smart_gap=true smart_border=true

	# define mouse mod and move/resize buttons
	dkcmd set mouse mod=alt move=button1 resize=button3


	# borders
	# ---------

	# set border width and colour for each window state
	# dkcmd set border width=1 colour focus='#6699cc' unfocus='#000000' urgent='#ee5555'

	# alternatively, enable split borders and colours
	dkcmd set border width=3 outer_width=1 \
		colour \
		focus='#3A3D42' \
		unfocus='#1B1C1F' \
		urgent='#C21A45' \
		outer_focus='#0E0F0F' \
		outer_unfocus='#0E0F0F' \
		outer_urgent='#0E0F0F'


	# window rules
	# --------------

	# rule class, instance, and title regexes are always case insensitive

	# open window(s) on a specific workspace (assigned monitor)
	# focus window and workspace on opening focus=true	
	dkcmd rule class="^firefox$" ws=3 focus=true
	dkcmd rule class="^thunderbird$" ws=3 focus=true
	dkcmd rule class="^gimp$" ws=4 focus=true
	dkcmd rule class="^vlc$" ws=5
	dkcmd rule class="^deadbeef$" ws=9 float=true focus=true

	# open window(s) and use a callback function (defined in config.h)
	# eg. mpv --x11-name=albumart /path/to/media
	dkcmd rule class="^mpv$" instance="^albumart$" float=true callback=albumart bw=0

	# open window(s) in a floating state
	dkcmd rule class="^(pavucontrol|transmission-gtk|steam|lxappearance)$" float=true

	# open window(s) with a specific geometry and coordinates (floating only!)
	dkcmd rule class="^google-chrome$" title="^open files$" float=true w=1280 h=720

	# open window(s) with sticky and floating enabled to view on all workspaces.
	dkcmd rule class="^stickyterm$" stick=true float=true w=1280 h=720

	# apply current rule set to all existing windows
	dkcmd rule apply '*'

	# delete all rules
	# dkcmd rule remove '*'

} >> "$logfile" 2>&1 # append responses

# inform of any errors in a notification
if grep -q 'error:' "$logfile"; then
	hash notify-send && notify-send -t 0 -u critical "dkrc has errors" \
		"$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"); print}' "$logfile")"
	exit 1
fi

exit 0
