#! /bin/sh

#killall -q conky &
#killall -q juiced &
#killall -q slstatus &

xsetroot -cursor_name left_ptr

#xrdb -l "$HOME/.Xresources" &
#xmodmap "$HOME/.Xmodmap" &

#numlockx on &

# battery monitor
#juiced -d

# wallpaper
# xsetroot -solid darkbliue &
# nitrogen --restore &
# "$HOME/.fehbg" &
# fbsetbg -c -r "$HOME/wallpaper/" &

# system info
# "$HOME/bin/conkybspwm.sh"
# "$HOME/.config/bspwm/tint2start.sh"
"$HOME/.config/bspwm/bspwm-bar.sh"

# key grabber
sxhkd &

bspc monitor -d 1: 2: 3: 4:

bspc config border_width         2
bspc config window_gap           0

bspc config top_padding          20
bspc config right_padding        0
bspc config bottom_padding       0
bspc config left_padding         0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#161516"
bspc config focused_border_color "#2E2A4F"
bspc config active_border_color "#2E2A4F"
bspc config urgent_border_color "#C11919"

bspc config pointer_modifier     mod1

bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a Thunderbird desktop='^4' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a XCalc state=floating
bspc rule -a Galculator state=floating
bspc rule -a XFontSel state=floating
bspc rule -a Sakura state=floating
bspc rule -a YadCal state=floating
bspc rule -a ColorBox state=floating
bspc rule -a FontBox state=floating
bspc rule "Yad-icon-browser" state=floating
bspc rule "Yad_Calendar" state=floating
# bspc rule "Gcolor2" state=floating
bspc rule -a gcolor2 state=floating center=true
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
